### ISSUE TITLE
Make Smartconfig When Timeout, Then do something?

### ISSUE THREAD

**Issue by komputerboy** [kakopappa/esp8266_smartconfig_flutter_example#3]
Hi, First i want to thank you for this project.

I want to ask how to check when Timeout occurs (when there is no esp8266 device), and then remove the loading display.

in this code:
```
  final String result = await platform.invokeMethod('startSmartConfig', <String, dynamic>{
          'ssid': _ssid,
          'bssid': _bssid,
          'pass': _password,
          'deviceCount': deviceCount,
          'broadcast': broadcast,
        }).timeout(_kLongTimeout);
```

**Comment by gustavofernandez** [comment]
> Hi, First i want to thank you for this project.
> 
> I want to ask how to check when Timeout occurs (when there is no esp8266 device), and then remove the loading display.
> 
> in this code:
> 
> ```
>   final String result = await platform.invokeMethod('startSmartConfig', <String, dynamic>{
>           'ssid': _ssid,
>           'bssid': _bssid,
>           'pass': _password,
>           'deviceCount': deviceCount,
>           'broadcast': broadcast,
>         }).timeout(_kLongTimeout);
> ```

Verify this code. The var "_resultResp" (must be a String) gets the answer if the connection has failed, otherwise it returns null.

Sorry for my English!

---------------------------------------------------------------------------------------------------------------


try {

      const String deviceCount = "1";
      const String broadcast = "1"; 

      final String result = await platform.invokeMethod('startSmartConfig', <String, dynamic>{
        'ssid': _ssid,
        'bssid': _bssid,
        'pass': _password,
        'deviceCount': deviceCount,
        'broadcast': broadcast,
        'resultResp' : _resultResp,
      });

      if(_resultResp != null)
      {
        output = _resultResp;
      }

      final parsed = json.decode(result);
      final devices = parsed["devices"];

      for (var device in devices) {
            output = "bssid: ${device["bssid"]} ip: ${device["ip"]}";
      }
      
    } on PlatformException catch (e) {
      output = "Failed to configure: '${e.message}'.";
    }

**Comment by gustavofernandez** [comment]
> > Hi, First i want to thank you for this project.
> > I want to ask how to check when Timeout occurs (when there is no esp8266 device), and then remove the loading display.
> > in this code:
> > ```
> >   final String result = await platform.invokeMethod('startSmartConfig', <String, dynamic>{
> >           'ssid': _ssid,
> >           'bssid': _bssid,
> >           'pass': _password,
> >           'deviceCount': deviceCount,
> >           'broadcast': broadcast,
> >         }).timeout(_kLongTimeout);
> > ```
> 
> Verify this code. The var "_resultResp" (must be a String) gets the answer if the connection has failed, otherwise it returns null.
> 
> Sorry for my English!
> 
> try {
> 
> ```
>   const String deviceCount = "1";
>   const String broadcast = "1"; 
> 
>   final String result = await platform.invokeMethod('startSmartConfig', <String, dynamic>{
>     'ssid': _ssid,
>     'bssid': _bssid,
>     'pass': _password,
>     'deviceCount': deviceCount,
>     'broadcast': broadcast,
>     'resultResp' : _resultResp,
>   });
> 
>   if(_resultResp != null)
>   {
>     output = _resultResp;
>   }
> 
>   final parsed = json.decode(result);
>   final devices = parsed["devices"];
> 
>   for (var device in devices) {
>         output = "bssid: ${device["bssid"]} ip: ${device["ip"]}";
>   }
>   
> } on PlatformException catch (e) {
>   output = "Failed to configure: '${e.message}'.";
> }
> ```


Or this code. I have been successful.

---------------------------------------------------------------------------------------------------------------

try {

      const String deviceCount = "1";
      const String broadcast = "1"; 

      final String result = await platform.invokeMethod('startSmartConfig', <String, dynamic>{
        'ssid': _ssid,
        'bssid': _bssid,
        'pass': _password,
        'deviceCount': deviceCount,
        'broadcast': broadcast,
        'resultResp' : _resultResp,
      });

      if(result == ""){
        output = _resultResp;

      }else{
        
        final parsed = json.decode(result);
        final devices = parsed["devices"];

        for (var device in devices) {
              output = "bssid: ${device["bssid"]} ip: ${device["ip"]}";
        }
      }
      
    } on PlatformException catch (e) {
      output = "Failed to configure: '${e.message}'.";
    }
